config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "plans#index"
  resources :users, only: [:edit, :update]
  resources :plans, only: [:index, :new, :create, :show, :destroy] do
    resources :contents, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :plan
  belongs_to :user

  validates :to_do, presence: true
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :plan_users, dependent: :destroy
  has_many :users, through: :plan_users
  has_many :contents, dependent: :destroy

  validates :title, presence: true
end

app/models/plan_user.rb
class PlanUser < ApplicationRecord
  belongs_to :plan
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true

  has_many :plan_users
  has_many :plans, through: :plan_users
  has_many :contents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]  # 環境変数を読み込む記述
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :company_name])
  end

end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :plan_find_params, only: [ :index, :create]
  before_action :move_to_index, only: [ :index]

  def index
    @content = Content.new
    @contents = @plan.contents.includes(:user)
  end

  def create
    @content = @plan.contents.new(contents_params)
    if @content.save
      redirect_to plan_contents_path(@plan), method: :get
    else
      @contents = @plan.contents.includes(:user)
      render :index
    end
  end

  private

  def contents_params
    params.require(:content).permit(:to_do).merge(user_id: current_user.id)
  end

 def plan_find_params
  @plan = Plan.find(params[:plan_id])
 end

  def move_to_index
    redirect_to root_path if @plan.plan_user_ids != current_user.id
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
before_action :move_to_index, only: [ :destroy]

  def index
    @plans = Plan.all
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)
    if @plan.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    plan = Plan.find(params[:id])
    plan.destroy
    redirect_to root_path
  end

  private

  def plan_params
    params.require(:plan).permit(:title, :start_time, :end_time, user_ids: [])
  end

  def move_to_index
    redirect_to root_path if @plan.user_id != current_user.id
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contents/_content.html.erb
<div class="content-detail">
  <div class="content-upper-detail">
    <div class="content-to_do">
      <!-- 投稿したメッセージ内容を記述する -->
      <%= content.to_do %>
    </div>
  </div>
  <div class="content-lower-detail">
      <div class="content-write-user">
        <!-- 投稿したユーザー名を出力する -->
        <%= content.user.name %>
      </div>
      <div class="content-detail-date">
        <!-- 投稿した時刻を出力する -->
        <%= l content.created_at %>
      </div>
  </div>
</div>

app/views/contents/_left_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
<%# 以下プランタイトル表示 %>
    <a href="#">Title</a>
  </div>
  <div class="create-content">
<%# 以下新規コンテンツ追加機能 %>
    <a href="#">内容を追加する</a>
  </div>
</div>

<div class="members">
<div class="member">
    <div class="member-name">
      <a href="#">Tom</a>
    </div>
  </div>
  <div class="member">
    <div class="member-name">
      <a href="#">Catherine</a>
    </div>
  </div>
</div>

app/views/contents/_main_contents.html.erb
<div class="contents-header">
  <div class="left-header">
    <div class="header-title">
      hogefuga
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <a href="#">予定削除</a>
    </div>
  </div>
</div>

<div class="content">
  <div class="detail">
    <div class="upper-detail">
      <div class="content-detail">
        予定内容
      </div>
    </div>
    <div class="lower-detail">
      <div class="write-user">
        Tom
      </div>
      <div class="detail-date">
        2020/3/31(Wed) 12:43:30
      </div>
    </div>
  </div>
</div>

<div class="form">
    <div class="form-input">
      <input class="form-comment" placeholder= "type a comment">
      <label class="form-image">
      <span class="image-file">画像</span>
      <input type="file" class="hidden">
      </label>
    </div>
    <input class="form-submit" type="submit" value="送信">
</div>

app/views/contents/index.html.erb
<div class="wrapper">
  <div class="content-side-bar">
  <%= render "plans/left_side_bar" %>
  </div>
  <div class="contents">
  <%= render "plans/main_contents" %>
  </div>
  <div class="content-right-side-bar">
   </div>
</div>
<div class="content-footer">
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plans/_left_side_bar.html.erb
<div class="side-bar-header">
  <div class="header-name">
    <%# logo %>
    <%= link_to image_tag("/images/smsrogo6.png", size:'60x60'), root_path %>
  </div>
  <div class="content-logo-text"> 
    SMS
  </div>
    <%# ここまで %>
</div>
<div class="plan-members-header">
       PlanMembers
   </div>
<div class="members">
  <div class="member">
     <% @plan.users.each do |user| %> 
        <li class="member-name">
         <%= user.name %>  
        </li>
      <%end%> 
  </div>
</div>

app/views/plans/_main_contents.html.erb
<div class="contents-header">
  <div class="left-header">
    <div class="header-title">
      <%# 以下プランタイトル表示 %>
     <%= @plan.title %>
      <%# ここまで %>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
     <%= link_to "予定を削除する", plan_path(@plan), method: :delete %>
    </div>
  </div>
</div>

<div class="content">
  <%= render partial: 'contents/content', collection: @contents %>
</div>

<%= form_with model: [@plan, @content], class: 'form', local: true do |f| %>
  <div class="form-input">
    <%= f.text_field :to_do, class: 'form-comment', placeholder: 'type a content' %>
    <label class="form-image">
      <span class="image-file">画像</span>
      <%= f.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/plans/index.html.erb
<div class='wrapper'>
  <div class='plan_side-bar'>
    <div class="plan_side-bar-header">
      <div class="plan_header-name">
       <%# logo %>
       <%= image_tag "/images/IMG_0188.PNG", :size =>'60x60'%>
     </div>
     <div class="logo-text"> 
       SMS
     </div>
     <%# ここまで %>
   </div>
   <%# 以下知り合い表示 %>
   <div class="friend-members-header">
       FriendMembers
  </div>
   <div class="friend-members">
     <div class="friend-member">
       <div class="friend-member-name">
         <a href="#">Tom</a>
       </div>
     </div>
     <div class="friend-member">
       <div class="friend-member-name">
         <a href="#">Catherine</a>
       </div>
     </div>
   </div>
   <%# ここまで %>
  </div>
  <div class="plan-contents">
      <div class="plan-contents-header">
        <div class="left-header">
          <div class="plan-header-title">
            <%# カレントユーザー表示 %>
            <%= current_user.name %>'s Plans
            <%# ここまで %>
          </div>
        </div>
        <div class="right-header">
          <div class="create-plan">
            <%# 以下新規予定追加機能 %>
            <%= link_to "CreatePlan", new_plan_path %>
            <%# ここまで %>
          </div>
          <div class="plan-header-button">
           <% if user_signed_in? %>
             <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
           <% end %>
          </div>
        </div>
      </div>
      <div class="plan-top">
        <div class="plan-content">
          <ul class='plan-lists'>
            <% current_user.plans.each do |plan| %>
              <li class='list'>
                <div class="plan-detail">
                  <div class="plan-upper-detail">
                    <div class="plan-content-detail">
                      <%= link_to(plan.title, plan_contents_path(plan.id), method: :get,class: "content-detail-title" )%>
                    </div>
                  </div>
                  <div class="plan-lower-detail">
                    <div class="plan-detail-date">
                      <%= l plan.created_at %>
                    </div>
                  </div>
                </div>
              </li>
           <% end %>
         </ul>
       </div>
        <%= month_calendar(events: @plans) do |date, plans| %>
          <%= date.day %>
          <% plans.each do |plan| %>
           <div>
             <%= link_to(plan.title, plan_contents_path(plan.id), method: :get) %>
           </div>
          <% end %>
        <% end %>
     </div>
  </div>
   <div class="plan-right-side-bar">
   </div>
</div>
<div class="plan-footer">
</div>

app/views/plans/new.html.erb
<div class='plan-form'>
  <h1>新規Plan</h1>
  <%=form_with model: @plan, local: true do |f|%>
    <div class='plan-form__field'>
      <div class='plan-form__field--left'>
        <%= f.label :予定タイトル, class: 'plan-form__label'%>
      </div>
      <div class='plan-form__field--right'>
        <%= f.text_field :title, class: 'plan_name plan-form__input', placeholder: 'Plan titleを入力してください'%>
      </div>
    </div>
    <div class='plan-form__field'>
      <div class="plan-form__field--left">
        <%= f.label :start_time %>
      </div>
      <div class='plan-form__field--right'> 
        <%= f.datetime_select :start_time %>
      </div>
    </div>
    <div class='plan-form__field'>
      <div class='plan-form__field--left'>
        <label class='plan-form__label' for='plan_プランメンバー'>プランメンバー</label>
      </div>
      <div class='plan-form__field--right'>
        <select name="plan[user_ids][]">
          <option value="">共有するユーザーを選択してください</option>
          <% User.where.not(id: current_user.id).each do |user| %>
            <option value=<%= user.id %>><%= user.name %></option>
          <% end %>
        </select>
        <input name="plan[user_ids][]" type="hidden" value=<%= current_user.id %>>
      </div>
    </div>
    <div class='plan-form__field'>
      <div class='plan-form__field--left'></div>
      <div class='plan-form__field--right'>
        <%= f.submit class: 'plan-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "TOPに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>